export default function PrintBox(props){
    return(
        <div className="AcontentBox">
            <h3>목록</h3>
            <table>
            <colgroup>
                <col width="10%"/>
                <col width="35%"/>
                <col width="25%"/>
                <col width="20%"/>
                <col width="10%"/>
            </colgroup>
                <thead>
                    <tr>
                        <th>
                            1
                        </th>
                        <th>
                            2
                        </th>
                        <th>
                            3
                        </th>
                        <th>
                            4
                        </th>
                        <th>
                            5
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            내용1
                        </td>
                        <td>
                            내용2
                        </td>
                        <td>
                            내용3
                        </td>
                        <td>
                            내용4
                        </td>
                        <td>
                            내용5
                        </td>
                    </tr>
                    <tr>
                        <td>
                            내용1
                        </td>
                        <td>
                            내용2
                        </td>
                        <td>
                            내용3
                        </td>
                        <td>
                            내용4
                        </td>
                        <td>
                            내용5
                        </td>
                    </tr>
                    <tr>
                        <td>
                            내용1
                        </td>
                        <td>
                            내용2
                        </td>
                        <td>
                            내용3
                        </td>
                        <td>
                            내용4
                        </td>
                        <td>
                            내용5
                        </td>
                    </tr>
                    <tr>
                        <td>
                            내용1
                        </td>
                        <td>
                            내용2
                        </td>
                        <td>
                            내용3
                        </td>
                        <td>
                            내용4
                        </td>
                        <td>
                            내용5
                        </td>
                    </tr>
                    <tr>
                        <td>
                            내용1
                        </td>
                        <td>
                            내용2
                        </td>
                        <td>
                            내용3
                        </td>
                        <td>
                            내용4
                        </td>
                        <td>
                            내용5
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    )
}